/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import models.bean.images;
import models.bean.multasCarros;
import models.dao.ImagesDAO;
import models.dao.multasDAO;

/**
 *
 * @author Guilherme
 */
public class Multas extends javax.swing.JFrame {

    BufferedImage imagemBuffer = null;
    ByteArrayOutputStream bytesImagem = new ByteArrayOutputStream();
    byte[] arrayByte;
    /**
     * Creates new form Multas
     */
    public Multas() {
        initComponents();
        
        DefaultTableModel modeloTabela = (DefaultTableModel) tabelaInformacoes.getModel();
        tabelaInformacoes.setRowSorter(new TableRowSorter(modeloTabela));

        readTabela();
    }
    
    public void readTabela() {
        DefaultTableModel modeloTabela = (DefaultTableModel) tabelaInformacoes.getModel();
        modeloTabela.setNumRows(0);
        
        multasDAO infoMultas = new multasDAO();
        
        infoMultas.read().forEach((multas) -> {
            modeloTabela.addRow(new Object[]{
                multas.getID_Multa(),
                multas.getNome(),
                multas.getCpf(),
                multas.getPlacaVeiculo(),
                multas.getTipoMulta(),
                multas.getValorMulta(),
            });
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textCpf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboMulta = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        textValorMulta = new javax.swing.JTextField();
        bttnSalvarImg = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaInformacoes = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        textPlaca = new javax.swing.JTextField();
        labelImagem = new javax.swing.JLabel();
        bttnSaveMulta = new javax.swing.JButton();
        bttnVoltar = new javax.swing.JButton();
        bttnAtualizarMulta = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel1.setText("Multas");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Nome :");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setText("CPF :");

        textCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCpfActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setText("Gravidade da Multa :");

        comboMulta.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        comboMulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Leve", "Média", "Grave", "Gravíssima" }));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setText("Valor da Multa :");

        bttnSalvarImg.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        bttnSalvarImg.setText("Salvar Imagem");
        bttnSalvarImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnSalvarImgActionPerformed(evt);
            }
        });

        tabelaInformacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Multa", "Nome", "CPF", "Placa", "Gravidade", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaInformacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaInformacoesMouseClicked(evt);
            }
        });
        tabelaInformacoes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaInformacoesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaInformacoes);
        if (tabelaInformacoes.getColumnModel().getColumnCount() > 0) {
            tabelaInformacoes.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setText("Placa do Veículo :");

        textPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPlacaActionPerformed(evt);
            }
        });

        labelImagem.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        labelImagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelImagem.setText("Inserir Imagem");
        labelImagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        labelImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelImagemMouseClicked(evt);
            }
        });

        bttnSaveMulta.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        bttnSaveMulta.setText("Cadastrar Multa");
        bttnSaveMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnSaveMultaActionPerformed(evt);
            }
        });

        bttnVoltar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bttnVoltar.setText("Voltar");
        bttnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnVoltarActionPerformed(evt);
            }
        });

        bttnAtualizarMulta.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        bttnAtualizarMulta.setText("Atualizar Multa");
        bttnAtualizarMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAtualizarMultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(textPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                    .addComponent(bttnSalvarImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(bttnVoltar)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(textValorMulta))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(comboMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bttnAtualizarMulta)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bttnSaveMulta)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(237, 237, 237))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(bttnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnSaveMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnAtualizarMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textValorMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bttnSalvarImg, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCpfActionPerformed

    public void getImagem() throws IOException {
        JFileChooser adicionarImagem = new JFileChooser();
        
        adicionarImagem.setFileFilter(new FileNameExtensionFilter("imagem", "bmp", "png", "jpg", "jpeg"));
        adicionarImagem.setAcceptAllFileFilterUsed(false);
        adicionarImagem.setDialogTitle("Selecionar imagem");
        adicionarImagem.showOpenDialog(this);
        
        if (adicionarImagem.getSelectedFile() != null) {
            String diretorio = "" + adicionarImagem.getSelectedFile().getAbsolutePath();

            imagemBuffer = ImageIO.read(new File(diretorio));
            Image redimensionarImagem = imagemBuffer.getScaledInstance(220, 100, 0);

            labelImagem.setText("");
            labelImagem.setIcon(new ImageIcon(redimensionarImagem));
        }
    }
    
    private void bttnSalvarImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnSalvarImgActionPerformed
        // TODO add your handling code here:
        
        images imagem = new images();
        ImagesDAO inserirImagem = new ImagesDAO();
        
        try {
            ImageIO.write(imagemBuffer, "jpg", bytesImagem);
            bytesImagem.flush();
            arrayByte = bytesImagem.toByteArray();
            bytesImagem.close();
            
            imagem.setImagem(arrayByte);
            inserirImagem.Save(imagem);
        } catch (IOException ex) {
            Logger.getLogger(Multas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bttnSalvarImgActionPerformed

    private void textPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPlacaActionPerformed

    private void labelImagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImagemMouseClicked
        try {
            this.getImagem();
        } catch (IOException ex) {
            Logger.getLogger(Multas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_labelImagemMouseClicked

    private void bttnSaveMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnSaveMultaActionPerformed
        // TODO add your handling code here:
        multasCarros newMulta = new multasCarros();
        multasDAO saveMultaBD = new multasDAO();
        
        newMulta.setValorMulta(Float.parseFloat(textValorMulta.getText()));
        newMulta.setNome(textNome.getText());
        newMulta.setCpf(textCpf.getText());
        newMulta.setTipoMulta((String) comboMulta.getSelectedItem());
        newMulta.setPlacaVeiculo(textPlaca.getText());
        
        saveMultaBD.create(newMulta);
        
        textValorMulta.setText("");
        textNome.setText("");
        textCpf.setText("");
        comboMulta.setSelectedItem("");
        textPlaca.setText("");
        
        readTabela();
    }//GEN-LAST:event_bttnSaveMultaActionPerformed

    private void tabelaInformacoesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaInformacoesKeyReleased
        // TODO add your handling code here
         if (tabelaInformacoes.getSelectedRow() != -1) {
            textNome.setText(tabelaInformacoes.getValueAt(tabelaInformacoes.getSelectedRow(), 1).toString());
            textCpf.setText(tabelaInformacoes.getValueAt(tabelaInformacoes.getSelectedRow(), 2).toString());
            textPlaca.setText(tabelaInformacoes.getValueAt(tabelaInformacoes.getSelectedRow(), 3).toString());
            textValorMulta.setText(tabelaInformacoes.getValueAt(tabelaInformacoes.getSelectedRow(), 5).toString());
        }
    }//GEN-LAST:event_tabelaInformacoesKeyReleased

    private void tabelaInformacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaInformacoesMouseClicked
        // TODO add your handling code here:
         if (tabelaInformacoes.getSelectedRow() != -1) {
            textNome.setText(tabelaInformacoes.getValueAt(tabelaInformacoes.getSelectedRow(), 1).toString());
            textCpf.setText(tabelaInformacoes.getValueAt(tabelaInformacoes.getSelectedRow(), 2).toString());
            textPlaca.setText(tabelaInformacoes.getValueAt(tabelaInformacoes.getSelectedRow(), 3).toString());
            textValorMulta.setText(tabelaInformacoes.getValueAt(tabelaInformacoes.getSelectedRow(), 5).toString());
        }
    }//GEN-LAST:event_tabelaInformacoesMouseClicked

    private void bttnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnVoltarActionPerformed
        // TODO add your handling code here:
        new Register().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bttnVoltarActionPerformed

    private void bttnAtualizarMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAtualizarMultaActionPerformed
        // TODO add your handling code here:
        if (tabelaInformacoes.getSelectedRow() != -1) {
            multasCarros attMulta = new multasCarros();
            multasDAO updateMulta = new multasDAO();
            
            attMulta.setNome(textNome.getText());
            attMulta.setCpf(textCpf.getText());
            attMulta.setID_Multa((int)tabelaInformacoes.getValueAt(tabelaInformacoes.getSelectedRow(), 0));
            
            updateMulta.update(attMulta);
         
            textValorMulta.setText("");
            textNome.setText("");
            textCpf.setText("");
            comboMulta.setSelectedItem("");
            textPlaca.setText("");
            
            readTabela();
        }
    }//GEN-LAST:event_bttnAtualizarMultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Multas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Multas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Multas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Multas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Multas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnAtualizarMulta;
    private javax.swing.JButton bttnSalvarImg;
    private javax.swing.JButton bttnSaveMulta;
    private javax.swing.JButton bttnVoltar;
    private javax.swing.JComboBox<String> comboMulta;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelImagem;
    private javax.swing.JTable tabelaInformacoes;
    private javax.swing.JTextField textCpf;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textPlaca;
    private javax.swing.JTextField textValorMulta;
    // End of variables declaration//GEN-END:variables
}
